
# ingress-controller 설치 명령어
# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/aws/deploy.yaml


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ordersystem-ingress
  namespace: prod
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:564290535730:certificate/1d84360a-8ea3-4fc1-adab-c60f21630c80
spec:
  ingressClassName: alb
  rules:
    - host: ordersystem.bagpacker4608.shop
      http:
        paths:
          - path: / #모든 url요청을 service로 라우팅
            pathType: Prefix
            backend:
              service:
                name: ordersystem-service
                port:
                  number: 80
