apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ordersystem-node-pool
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"] # 스팟 위주 운영 시 유용
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ordersystem-node-class
  limits:
    cpu: 1000 # 클러스터 최대 CPU 상한선 제한