# secret 생성 명령어
# kubectl -n prod create secret generic ordersystem-secret \
# --from-literal=DB_HOST=my-database.cjucmemci7jg.ap-northeast-2.rds.amazonaws.com \
# --from-literal=DB_PW=B7IJrZtiKwPOTDkLH4a0

# Secret 생성시 Base64 인코딩되어 Data 생성